#!/bin/bash 

. exec/system/config/allg.sh
. exec/system/shell/allg/file.sh

mne_error_ignore=1
$sambabin/samba-tool user delete $olduser >&$logfile 2>&1
mne_error_ignore=

. $(dirname $BASH_SOURCE)/del_standalone
