#!/bin/bash

mne_error_ignore=1
uid=$(id -u $user 2>&$logfile)
result=$?
mne_error_ignore=

if [ "$result" = "0" ];then
  gid=$(id -g $user 2>&$logfile)
  get_data "$updateuser" $user $uid $gid 1>&$logfile 2>&1
else
  get_data "$updateuser" $user "" "" 1>&$logfile 2>&1
fi
