#!/bin/bash

exit_status=0

. exec/system/config/allg.sh
. exec/system/shell/allg/file.sh

find_script domain/detail read.sh
find_script user/data read.sh

olduser=$valoginnameInput_old
valoginnameInput=$vapar2
password=$(dd if=/dev/urandom bs=2048 count=1 2>/dev/null |tr -dc "a-zA-Z0-9"|fold -w 64 |head -1)

if [ ! "$valoginnameInput" = "" ]; then
    userdata=`get_data "$getuserdata" "$valoginnameInput"`
    get_userdata "$userdata"
fi

. exec/system/shell/domain/user/move 

exit $exitstatus