#!/bin/bash

. exec/system/config/allg.sh
. exec/system/shell/allg/file.sh

. exec/system/shell/allg/db.sh

. $(dirname $BASH_SOURCE)/definitions
. $(dirname $BASH_SOURCE)/functions

case ${DISTRIB_RELEASE,,} in
  12.04|14.04|16.04) . $(dirname $BASH_SOURCE)/rdconfig_interface;;
  *)                 . $(dirname $BASH_SOURCE)/rdconfig_netplan;;
esac
