#!/bin/bash

. exec/system/config/allg.sh
. exec/system/shell/allg/file.sh

find_script network read.sh

. $(dirname $BASH_SOURCE)/rdconfig

case ${DISTRIB_RELEASE,,} in
  debian_10|ubuntu_16.04) . $(dirname $BASH_SOURCE)/wrconfig_interface;;
  ubuntu_18.04)           . $(dirname $BASH_SOURCE)/wrconfig_netplan;;
esac

  