#!/bin/bash

. exec/system/config/allg.sh
. exec/system/shell/allg/file.sh

find_script network read.sh

. $(dirname $BASH_SOURCE)/rdconfig

case ${DISTRIB_ID,,} in
  debian_10)     . $(dirname $BASH_SOURCE)/wrconfig_interface;;
  raspbian_10)   . $(dirname $BASH_SOURCE)/wrconfig_dhcpcd;;
  ubuntu_18.04)  . $(dirname $BASH_SOURCE)/wrconfig_netplan;;
esac

  