#!/bin/bash

. exec/system/config/allg.sh
. exec/system/shell/allg/file.sh

find_script network read.sh

. $(dirname $BASH_SOURCE)/rdconfig

case ${DISTRIB_RELEASE,,} in
  12.04|14.04|16.04) . $(dirname $BASH_SOURCE)/wrconfig_interface;;
  *)                 . $(dirname $BASH_SOURCE)/wrconfig_netplan;;
esac

  