#!/bin/bash

exit_status=0

vaadminpasswordInputignore=1

. exec/system/config/allg.sh
. exec/system/shell/allg/file.sh
. $scriptdir/functions

find_script domain/dns read.sh

read_domain
if [ "$typ" = "primary" ]; then

  acttime=$(date +%s)
  check_passwd

  prog='/^    A:/  { print $2;}'
  oldaddr=$(samba-tool dns query $(hostname) $domain $vapar1 $vapar3 -k yes 2>&$logfile | awk "$prog")

  if [ "$oldaddr" = "" ];then
    if [ "$vapar0" != "" ]; then
      prog='/^  Name=/ { split($1,n,"="); sub(/,/,"",n[2]); name=n[2]; next }
             /^    A:/ { if ( $2 == "'$vapar2'" ) { print name; exit } }'
      oldname=$(samba-tool dns query $(hostname) "$domain" '@' "A" | awk "$prog" ) 
      if [ "$oldname" != '' ]; then
        samba-tool dns delete $(hostname) $domain $oldname A $vapar2 -k yes
      fi
    fi
    samba-tool dns add $(hostname) $domain $vapar1 $vapar3 "$vapar2" -k yes
  elif [ "$oldaddr" != "$vapar2" ]; then
    samba-tool dns update $(hostname) $domain $vapar1 $vapar3 $oldaddr $vapar2 -k yes
  fi  

  . $scriptdir/../dhcp/mkfix

fi

