#!/bin/bash

find_template conffile domain/enable smb_$typ.conf

i=`dpkg --get-selections mnesamba | expand | fgrep ' install' | wc -l`
if [ ! "$i" = "1" ]; then
    apt-get update > /dev/null 2>&1
    apt-get install mnesamba > /dev/null 2>&1
fi

systemctl daemon-reload

mne_error_ignore=1
systemctl stop    mne_sogo.service 2>&$logfile 1>&2
systemctl disable mne_sogo.service 2>&$logfile 1>&2

systemctl stop    mne_samba.service 2>&$logfile 1>&2
systemctl disable mne_samba.service 2>&$logfile 1>&2

systemctl stop    bind9.service 2>&$logfile 1>&2
systemctl disable bind9.service 2>&$logfile 1>&2

systemctl enable mne_smb.service 2>&$logfile 1>&2
systemctl enable mne_nmb.service 2>&$logfile 1>&2
mne_error_ignore=

# -------------------------------------------
# samba konfigurieren
# -------------------------------------------

mkdir -p /var/log/samba 2>/dev/null

prog='/####DOMAIN####/  {   gsub(/####DOMAIN####/, domain);  }
      /####WORKGROUP####/ { gsub(/####WORKGROUP####/,workgroup); }
      /####DESCRIPTION####/ { gsub(/####DESCRIPTION####/,description); }
                          { print $0 }'

mkdir -p $sambaconf > /dev/null 2>&1
if [ -f "$sambaconf/smb.conf" ]; then
   mv "$sambaconf/smb.conf" "$sambaconf/samba.conf"_`date +"%d.%m.%Y_%H:%M:%S"`
fi
awk "$prog" "workgroup=$workgroup" "domain=$domain" "description=$description" $conffile > $sambaconf/smb.conf

mod_dhclient "" "" ""

systemctl daemon-reload
systemctl restart mne_smb.service      2>&$logfile 1>&2
systemctl restart mne_nmb.service      2>&$logfile 1>&2
