#!/bin/bash

exit_status=0

vaadminpasswordInputignore=1

. exec/system/config/allg.sh
. exec/system/shell/allg/file.sh

find_script domain/detail read.sh
domainconf=`get_data "$getdomain"`
get_domain "$domainconf"

if [ "$description" = "" ]; then
    description="%h server (Samba, Ubuntu)"
fi

export PATH=$sambabin:$sambasbin:$PATH

. $scriptdir/functions
. $scriptdir/enable_$typ
. $scriptdir/../share/enable
