#!/bin/bash

exit_status=0

vaadminpasswordInputignore=1

. exec/system/config/allg.sh
. exec/system/shell/allg/file.sh

find_script domain/detail read.sh
domainconf=`get_data "$getdomain"`
get_domain "$domainconf"

if [ "$description" = "" ]; then
    description="%h server (Samba,Nelson - technische Informatik)"
fi

udomain=$(echo "$domain"| awk '{print toupper($0)}')
domaindn=$(echo $domain | sed -e "s/^/dc=/" -e "s/\./,dc=/g")

export PATH=$sambabin:$sambasbin:$PATH

. $(dirname $BASH_SOURCE)/functions
. $(dirname $BASH_SOURCE)/enable_$typ

if [ "$typ" = "standalone" ]; then
  . $(dirname $BASH_SOURCE)/../dhcp/disable
else
  . $(dirname $BASH_SOURCE)/../dhcp/enable
fi
