#!/bin/bash

function add_host()
{
    local addr=$1
    local hostname=$2
    local domain=$3

    egrep "$(echo $addr | sed -e 's@\.@\\.@g')[ 	]+$hostname.$domain" /etc/hosts >&$logfile 2>&1
    if [ ! "$?" = "0" ]; then
      egrep "^[ 	]*[^#].*$hostname.$domain" /etc/hosts >&$logfile 2>&1
      if [ "$?" = "0" ];then
          sed -e "s/^[ 	]*\([^ 	]\{1,\}\)\(.*$hostname\.$domain\)/$(echo $addr | sed -e 's@\.@\\.@g')\2/1" < /etc/hosts > /tmp/hosts$$
      else
          sed -e "1i$addr    $hostname.$domain $hostname" < /etc/hosts > /tmp/hosts$$
      fi
      mv /tmp/hosts$$ /etc/hosts
    fi

}

function add_users()
{
  get_data "$getuser" | \
  while read line; 
  do
     get_user "$line"
     mne_error_ignore=1
     id $user 1>&$logfile 2>&1
     result=$?
     mne_error_ignore=
     
     if [ "$result" = "0" ]; then
         $sambabin/samba-tool user create "$user" --random-password --rfc2307-from-nss
     else
         $sambabin/samba-tool user create "$user" --random-password
     fi
  done
}

function mod_dhclient()
{
if [ -f $dhcpconfig ]; then
	sed -e "\$a\\
# mnesamba_conf start\\
supersede domain-name-servers $1;\\
supersede domain-name \"$2\";\\
supersede domain-search \"$2\";\\
# mnesamba_conf end" < $dhcpconfig > /tmp/dhclient.$$

    mv /tmp/dhclient.$$ $dhcpconfig
fi

}

function mod_smbconf()
{
    local prog="/\[global\]/ { start=1; print \$0; next;}
   /^[    ]*$|^\[/  { if ( start == 1 )
                    {
                      print \"        include = $sambaconf/globalextra.conf\";
                      print \"        include = $sambaconf/dhcp.conf\";
                      start = 2;
                     }
                   }
                   { print \$0; }
               END { print \"include = $sambaconf/shares.conf\"; } "
    
    awk "$prog" < $sambaconf/smb.conf  > /tmp/smb.$$
    mv /tmp/smb.$$ $sambaconf/smb.conf;
    
    touch $sambaconf/globalextra.conf;
    touch $sambaconf/dhcp.conf;
    touch $sambaconf/shares.conf;
}

function mod_kerberos()
{
    if [ -f $kerberosconfig ]; then
        echo "[libdefaults]
    dns_lookup_realm = false
    dns_lookup_kdc = true
    default_realm = $1
        " "$(sed -e '/^\[libdefaults\]/,/^[   ]*$/d' < $kerberosconfig )" > /tmp/$$
        mv /tmp/$$ $kerberosconfig
    else
        echo "[libdefaults]
    dns_lookup_realm = false
    dns_lookup_kdc = true
    default_realm = $1
        " > $kerberosconfig
    fi
}

function rm_config()
{
    rm -rf /var/run/samba/* >&$logfile 2>&1
    rm -rf /var/lib/mne/samba   >&$logfile 2>&1

    for dir in cache lib lock locks private run
    do
        mkdir -p /var/lib/mne/samba/$dir 2>&1
    done

    # -------------------------------------------
    # check name-server in dhclient.conf
    # -------------------------------------------

    if [ -f $dhcpconfig ]; then
        sed -e "/mnesamba_conf start/,/mnesamba_conf end/d" < $dhcpconfig > /tmp/dhclient.$$
        mv /tmp/dhclient.$$ $dhcpconfig
    fi

    mne_ignore_error=1
    if [ -f $sambaconf/smb.conf ];then
        rm $sambaconf/smb.conf >&$logfile 2>&1
        rm $sambaconf/validuser.conf >&$logfile 2>&1
        rm $sambaconf/shares.conf >&$logfile 2>&1
        rm $sambaconf/globalextra.conf >&$logfile 2>&1
    fi
    mne_ignore_error=
}
