#!/bin/bash

# -------------------------------------------
# check address is in /etc/hosts
# -------------------------------------------
addr=$(ip addr show $netdevice | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
add_host $addr $(hostname) $domain

mod_netpar

# -------------------------------------------
# resolv.conf konfigurieren
# -------------------------------------------

save_file /etc/resolv.conf
rm -f /etc/resolv.conf
echo "nameserver $addr" > /etc/resolv.conf
echo "domain $domain" >> /etc/resolv.conf
echo "search $domain $dnssearch" >> /etc/resolv.conf

systemctl stop systemd-resolved >/dev/null 2>&1
systemctl disable systemd-resolved >/dev/null 2>&1

systemctl restart mne_samba.service
systemctl restart bind9.service

. $(dirname $BASH_SOURCE)/../dhcp/enable
