#!/bin/bash

openssl req -in $certcsrdir/$domain.csr -noout -text | \
  awk '/Subject Alternative Name/ { p=1; next; } { if ( p ) { gsub(" " , ""); printf("subjectAltName=%s\n", $0); exit } } ' > $(dirname $BASH_SOURCE)/multi.cnf

echo $vapasswdInput | openssl x509 -req -days 365 -extfile $(dirname $BASH_SOURCE)/multi.cnf \
		     -in $certcsrdir/$domain.csr -CA $certcadir/ca.crt -CAkey $certcadir/ca.key -CAcreateserial -CAserial $certcadir/serial.seq -out $certcertdir/$domain.crt -passin stdin  >&$logfile 2>&1

if [ "$?" != "0" ]; then
    rm -f $certcertdir/$domain.crt 2>&$logfile >/dev/null
else
    chmod 644 $certcertdir/$domain.crt
fi   

rm -f $(dirname $BASH_SOURCE)/multi.cnf
